# Generated by Django 6.0.3 on 2026-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-en_cartelera', 'titulo'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.TextField(blank=True, help_text='Separar actores con comas', null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('ATP', 'Apta para todo público'), ('+13', 'Mayores de 13 años'), ('+16', 'Mayores de 16 años'), ('+18', 'Mayores de 18 años')], default='ATP', max_length=5),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='en_cartelera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(blank=True, choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia Ficción'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('animacion', 'Animación'), ('documental', 'Documental')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
