# Generated by Django 6.0.3 on 2026-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_pelicula_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-en_cartelera', 'titulo'], 'verbose_name': 'Pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
