# Generated by Django 6.0.3 on 2026-07-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_pelicula_options_alter_pelicula_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visto', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Película Vista',
                'verbose_name_plural': 'Películas Vistas',
                'ordering': ['-fecha_visto'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.CreateModel(
            name='RatingPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], help_text='Puntuación de 1 a 5 estrellas')),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Película',
                'verbose_name_plural': 'Calificaciones de Películas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
