# Generated by Django 6.0.3 on 2026-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='codigo_qr',
            field=models.CharField(blank=True, help_text='Código único para QR', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='escaneado_por',
            field=models.CharField(blank=True, help_text='Usuario/personal que escaneó el QR', max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_escaneo',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se escaneó el QR', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='qr_escaneado',
            field=models.BooleanField(default=False, help_text='Indica si el QR fue escaneado al ingresar'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
