# Generated by Django 6.0.3 on 2026-06-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_codigo_qr_pago_escaneado_por_pago_fecha_escaneo_and_more'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='promociones.combo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cupon_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='promociones.cupon'),
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento_cupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento_promo_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto antes de descuentos', max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='precio_combo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='promo_dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='promociones.promociondia'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto final pagado', max_digits=10),
        ),
    ]
