# Generated by Django 6.0.3 on 2026-07-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_combo_pago_cupon_usado_pago_descuento_cupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria')], max_length=20),
        ),
    ]
