# Generated by Django 6.0.3 on 2026-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cantidad_combo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
