# Generated by Django 6.0.3 on 2026-07-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pago_cantidad_combo'),
        ('promociones', '0002_combo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pago', to='promociones.combo')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Ítem de Pago',
                'verbose_name_plural': 'Ítems de Pago',
            },
        ),
    ]
