# Generated by Django 6.0.3 on 2026-03-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_pelicula_options_alter_pelicula_titulo'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='funcion',
            index=models.Index(fields=['sala', 'fecha_hora'], name='salas_funci_sala_id_de616b_idx'),
        ),
    ]
