# Generated by Django 6.0.3 on 2026-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_funcion_salas_funci_sala_id_de616b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=12, help_text='Cantidad de columnas (1, 2, 3, ...)'),
        ),
        migrations.AddField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=10, help_text='Cantidad de filas (A, B, C, ...)'),
        ),
    ]
