# Generated by Django 6.0.3 on 2026-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_sala_columnas_sala_filas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(default=0, editable=False, help_text='Se calcula automáticamente: filas*columnas'),
        ),
    ]
