# Generated by Django 6.0.3 on 2026-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_alter_sala_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('2d', '2D'), ('3d', '3D'), ('2d_premium', '2D Premium'), ('3d_premium', '3D Premium (IMAX/DBOX)')], default='2d', help_text='Tipo de tecnología de la sala', max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=8, help_text='Cantidad de columnas (1, 2, 3, ...)'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=6, help_text='Cantidad de filas (A, B, C, ...)'),
        ),
    ]
