# Generated by Django 6.0.3 on 2026-07-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_sala_tipo_alter_sala_columnas_alter_sala_filas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_codigo', models.CharField(help_text='Código del asiento, ej: A1', max_length=10)),
                ('motivo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('vip', 'VIP'), ('admin', 'Reservado por Admin'), ('reservado', 'Reservado (cortesía/especial)')], default='admin', max_length=20)),
                ('nota', models.CharField(blank=True, help_text='Motivo puntual, opcional (ej: butaca rota, avisado 03/07)', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('funcion', models.ForeignKey(blank=True, help_text='Dejar vacío para bloqueo permanente en toda la sala. Completar para bloquear solo en esta función.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_asientos', to='salas.funcion')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_asientos', to='salas.sala')),
            ],
            options={
                'verbose_name': 'Asiento Bloqueado',
                'verbose_name_plural': 'Asientos Bloqueados',
                'ordering': ['sala', 'asiento_codigo'],
                'constraints': [models.UniqueConstraint(fields=('sala', 'asiento_codigo', 'funcion'), name='unico_bloqueo_por_asiento_funcion')],
            },
        ),
    ]
