# Generated by Django 6.0.3 on 2026-07-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_asientobloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=8, help_text='Cantidad de columnas (1, 2, 3, ...)Cantidad TOTAL de columnas del lienzo de la sala (1, 2, 3, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=6, help_text='Cantidad de filas (A, B, C, ...)Cantidad TOTAL de filas del lienzo de la sala (A, B, C, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(default='SALA', max_length=100),
        ),
        migrations.CreateModel(
            name='SeccionSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lateral Izquierdo, Centro, Palcos', max_length=50)),
                ('fila_inicio', models.PositiveIntegerField(help_text='Primera fila (1 = A, 2 = B, ...)')),
                ('fila_fin', models.PositiveIntegerField(help_text='Última fila incluida')),
                ('columna_inicio', models.PositiveIntegerField(help_text='Primera columna')),
                ('columna_fin', models.PositiveIntegerField(help_text='Última columna incluida')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='salas.sala')),
            ],
            options={
                'verbose_name': 'Sección de Sala',
                'verbose_name_plural': 'Secciones de Sala',
                'ordering': ['sala', 'fila_inicio', 'columna_inicio'],
            },
        ),
    ]
