# Generated by Django 6.0.3 on 2026-07-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_alter_sala_columnas_alter_sala_filas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=8, help_text='Cantidad TOTAL de columnas del lienzo de la sala (1, 2, 3, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=6, help_text='Cantidad TOTAL de filas del lienzo de la sala (A, B, C, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
    ]
