# Generated by Django 6.0.3 on 2026-07-12 21:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_alter_sala_columnas_alter_sala_filas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='multiplicador_precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplica el precio base de la entrada para funciones en esta sala (1.00 = precio normal, 1.25 = +25%, etc). Libre: podés usar el valor sugerido de tu tipo de sala o poner cualquier otro.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='asientobloqueado',
            name='motivo',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('reservado', 'Reservado')], default='mantenimiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio manual de esta función. Si lo dejás vacío, se calcula automáticamente: precio base configurado x multiplicador de la sala.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=10, help_text='Cantidad TOTAL de columnas del lienzo de la sala (1, 2, 3, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=10, help_text='Cantidad TOTAL de filas del lienzo de la sala (A, B, C, ...). Si la sala tiene secciones, ninguna puede exceder este valor.'),
        ),
        migrations.CreateModel(
            name='CategoriaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_codigo', models.CharField(help_text='Código del asiento, ej: A1', max_length=10)),
                ('nombre', models.CharField(default='Mejorado', help_text='Nombre de la categoría, ej: Mejorado, Confort, Primera fila', max_length=50)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Se aplica sobre el precio final de la función para este asiento puntual (1.25 = +25%, 1.50 = +50%, etc).', max_digits=4)),
                ('color', models.CharField(default='#f1c40f', help_text='Color hex para mostrar este asiento en el mapa, ej: #f1c40f', max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_asientos', to='salas.sala')),
            ],
            options={
                'verbose_name': 'Categoría de Asiento',
                'verbose_name_plural': 'Categorías de Asientos',
                'ordering': ['sala', 'asiento_codigo'],
                'constraints': [models.UniqueConstraint(fields=('sala', 'asiento_codigo'), name='unica_categoria_por_asiento')],
            },
        ),
    ]
