# Generated by Django 6.0.3 on 2026-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0009_sala_multiplicador_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio manual de esta función. Si lo dejás vacío, se calcula automáticamente: precio base configurado x multiplicador de la sala.', max_digits=10, null=True),
        ),
    ]
