# Generated by Django 6.0.3 on 2026-06-01 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0004_reserva_asientos_seleccionados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(help_text='Ej: 1 entrada + Pochoclo grande + Bebida 500ml', max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='combos/')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único (ej: DESC25, VERANO10)', max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto_fijo', 'Monto Fijo ($)')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: 25 = 25%. Si es monto fijo: 500 = $500', max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usos_maximos', models.IntegerField(blank=True, help_text='Dejar vacío para usos ilimitados', null=True)),
                ('usos_actuales', models.IntegerField(default=0, editable=False)),
                ('activo', models.BooleanField(default=True)),
                ('solo_primera_compra', models.BooleanField(default=False, help_text='Solo válido para usuarios sin compras previas')),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de compra para poder aplicar el cupón', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PromocionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('tipo', models.CharField(choices=[('2x1', '2x1 — Pagás una entrada, llevás dos'), ('descuento', 'Descuento porcentual')], max_length=20)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, help_text="Solo para tipo 'Descuento porcentual'", max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción visible para el usuario')),
            ],
            options={
                'verbose_name': 'Promoción por Día',
                'verbose_name_plural': 'Promociones por Día',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='CuponUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(default=django.utils.timezone.now)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='promociones.cupon')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupon_usado', to='reservas.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_usados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón Usado',
                'verbose_name_plural': 'Cupones Usados',
                'ordering': ['-fecha_uso'],
            },
        ),
    ]
