# Generated by Django 6.0.3 on 2026-07-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='categoria',
            field=models.CharField(choices=[('combo', 'Combo'), ('bebida', 'Bebida'), ('snack', 'Snack'), ('pochoclo', 'Pochoclo')], default='combo', max_length=20),
        ),
    ]
