# Generated by Django 6.0.3 on 2026-08-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_cupon_sede_promociondia_sede_combo_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='categoria',
            field=models.CharField(default='combo', max_length=20),
        ),
    ]
