# Generated by Django 6.0.3 on 2026-07-13 05:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_entrada_base', models.DecimalField(decimal_places=2, default=Decimal('4500.00'), help_text='Precio base de una entrada, antes de aplicar el multiplicador de la sala. Se usa solo cuando una Función no tiene un precio manual cargado.', max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
    ]
