# Generated by Django 6.0.3 on 2026-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_backend',
            field=models.CharField(choices=[('console', 'Consola (desarrollo — los mails se imprimen en la terminal, no se envían)'), ('smtp', 'SMTP (Gmail, Mailtrap, u otro servidor)')], default='console', help_text="Con 'Consola' no se manda ningún mail real, queda solo para pruebas. Para mandar mails de verdad, elegí SMTP y completá los datos de abajo.", max_length=10),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_from',
            field=models.CharField(blank=True, help_text='Ej: Cine Online <noreply@cineonline.com>', max_length=200),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_host',
            field=models.CharField(blank=True, help_text='Ej: smtp.gmail.com o sandbox.smtp.mailtrap.io', max_length=200),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Contraseña o contraseña de aplicación de la cuenta SMTP. Se guarda como texto plano en la base de datos, igual que estaba en settings.py — no es apto para producción real, pero sirve para este proyecto.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Usuario/email de la cuenta SMTP', max_length=200),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 587 (Gmail) o 2525 (Mailtrap)', null=True),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='max_asientos_por_reserva',
            field=models.PositiveIntegerField(default=6, help_text='Cantidad máxima de asientos que un usuario puede reservar en una sola operación.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='qr_minutos_antes_funcion',
            field=models.PositiveIntegerField(default=120, help_text='Minutos antes del horario de la función en que se habilita el escaneo del código QR de la entrada. Ejemplo: 120 = se puede escanear desde 2 horas antes.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tiempo_limite_pago_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Minutos que tiene el usuario para completar el pago desde que entra a seleccionar asientos. Pasado ese tiempo, la reserva se cancela automáticamente.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tmdb_api_key',
            field=models.CharField(blank=True, help_text='API key de The Movie Database, usada por el importador de películas (Panel > Películas > Buscar en TMDB). Si se deja vacío, se usa la que esté cargada en settings.py.', max_length=200),
        ),
    ]
