# Generated by Django 6.0.3 on 2026-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
