# Generated by Django 6.0.3 on 2026-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_fecha_limite_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asientos_seleccionados',
            field=models.CharField(blank=True, help_text='Asientos separados por coma. Ej: A1,A2,B5', max_length=500, null=True),
        ),
    ]
